/*
 * frmCompany.java
 *
 * Created on 24 Kasým 2007 Cumartesi, 17:58
 */

package askan;
import askan.configuration.*;
import askan.systems.*;
import askan.steelyard.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author  Kerem
 */
public class frmCompany extends javax.swing.JFrame {
    
    private askan.systems.CompanyProcess companyProcess;
    
    /** Creates new form frmCompany */
    public frmCompany() {
        ActionMap am;
        InputMap im;
        KeyStroke ks;          
        
        initComponents();
        companyProcess = new CompanyProcess();
        
        Action plateActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnPlateActionPerformed(actionEvent);
            }
          };        
        am = btnPlate.getActionMap();
        im = btnPlate.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        im.put(ks, "plate");
        am.put("plate", plateActionListener);    
        
        Action saveActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnSaveActionPerformed(actionEvent);
            }
          };        
        am = btnSave.getActionMap();
        im = btnSave.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F11, 0);
        im.put(ks, "save");
        am.put("save", saveActionListener);  
        
        Action weighActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnWeigh1ActionPerformed(actionEvent);
            }
          };        
        am = btnWeigh1.getActionMap();
        im = btnWeigh1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0);
        im.put(ks, "weigh");
        am.put("weigh", weighActionListener);          
        
        Action closeActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnCloseActionPerformed(actionEvent);
            }
          };        
        am = btnClose.getActionMap();
        im = btnClose.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        im.put(ks, "close");
        am.put("close", closeActionListener);          
        
        this.setTitle("Þirket Aracý Tartýmý");
        setStatus("Lütfen çekici ve (varsa) dorse plakasýný girip sorgulayýn");
        
        txtWeight1.setEditable(Main.config.intParam.manualWeight);
        txtVrkme1.setEditable(Main.config.intParam.manualWeight);
        txtWeight2.setEditable(Main.config.intParam.manualWeight);
        txtVrkme2.setEditable(Main.config.intParam.manualWeight);       
        txtWeightTotal.setEditable(Main.config.intParam.manualWeight);
        txtVrkmeTotal.setEditable(Main.config.intParam.manualWeight);               
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPlate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPlate2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtWeight1 = new javax.swing.JTextField();
        txtWeight2 = new javax.swing.JTextField();
        txtWeightTotal = new javax.swing.JTextField();
        txtVrkme1 = new javax.swing.JTextField();
        txtVrkme2 = new javax.swing.JTextField();
        txtVrkmeTotal = new javax.swing.JTextField();
        btnWeigh1 = new javax.swing.JButton();
        btnPlate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/save_16.gif"))); // NOI18N
        btnSave.setText("F11 - Kaydet");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/delete_16.gif"))); // NOI18N
        btnClose.setText("F12 - Kapat");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblStatus.setText("...");
        lblStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Çekici");

        txtPlate.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Dorse");

        txtPlate2.setFont(new java.awt.Font("Tahoma", 0, 14));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Çekici Aðýrlýðý");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("Dorse Aðýrlýðý");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("Toplam");

        txtWeight1.setEditable(false);
        txtWeight1.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtWeight2.setEditable(false);
        txtWeight2.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtWeightTotal.setEditable(false);
        txtWeightTotal.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkme1.setEditable(false);
        txtVrkme1.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkme2.setEditable(false);
        txtVrkme2.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeTotal.setEditable(false);
        txtVrkmeTotal.setFont(new java.awt.Font("Tahoma", 0, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtWeightTotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeight2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeight1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVrkme1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrkme2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrkmeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtWeight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtWeight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtWeightTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtVrkme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVrkme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVrkmeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnWeigh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/applications_16.gif"))); // NOI18N
        btnWeigh1.setText("F5 - Tart");
        btnWeigh1.setEnabled(false);
        btnWeigh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeigh1ActionPerformed(evt);
                btnWeigh1jButton1ActionPerformed(evt);
            }
        });

        btnPlate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/add_16.gif"))); // NOI18N
        btnPlate.setText("F1 - Seç");
        btnPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(txtPlate2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlate, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(btnWeigh1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPlate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWeigh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addComponent(lblStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        btnSave.setEnabled(false);
        setStatus("Aðýrlýklar kaydediliyor...");
        
        companyProcess.dateWeight = Calendar.getInstance();
        
        try
        {
            companyProcess.insert(Main.sql);
            setStatus("Aðýrlýklar kaydedildi...");
        }
        catch(Exception ex)
        {
            setStatus("Aðýrlýklar kaydedilirken bir hata oluþtu...");
            Main.appendLog(ex.toString());
            btnSave.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnWeigh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeigh1ActionPerformed
        btnWeigh1.setEnabled(false);
        
        if (companyProcess.getWeightStyle() == CompanyProcess.WEIGHT_STYLE.SINGLE)
        {
            if (Main.config.intParam.manualWeight)
            {
                try
                {
                companyProcess.emptyWeight = new Weight();
                companyProcess.emptyWeight.setWeight(txtWeight1.getText(), txtVrkme1.getText());                    
                }
                catch(Exception ex)
                {
                    Main.appendLog("Aðýrlýk hatasý: " + ex.toString());
                    setStatus("Lütfen aðýrlýklarý kontrol edin");
                    return;
                }
            }
            else
            {
                Main.steelYard.truckStatus = askan.steelyard.TwoWaySerialComm.TRUCK_STATUS.EMPTY;
                companyProcess.emptyWeight = Main.steelYard.getLastWeight();
            }
        }
        else
        {
            if (Main.config.intParam.manualWeight)
            {
                try
                {
                companyProcess.fullWeight = new Weight();
                companyProcess.fullWeight.setWeight(txtWeightTotal.getText(), txtVrkmeTotal.getText());
                }
                catch(Exception ex)
                {
                    Main.appendLog("Aðýrlýk hatasý: " + ex.toString());
                    setStatus("Lütfen aðýrlýklarý kontrol edin");
                    return;
                }                
            }
            else
            {
                Main.steelYard.truckStatus = askan.steelyard.TwoWaySerialComm.TRUCK_STATUS.FULL;
                companyProcess.fullWeight = Main.steelYard.getLastWeight();
            }
        }
        
        companyProcess.calculateCalcWeight();
        
        if (!Main.config.intParam.manualWeight)
        {
            txtWeight1.setText(companyProcess.emptyWeight.toString(false));
            txtVrkme1.setText(companyProcess.emptyWeight.getUOM());
            
            txtWeightTotal.setText(companyProcess.fullWeight.toString(false));
            txtVrkmeTotal.setText(companyProcess.fullWeight.getUOM());            
        }
        
        txtWeight2.setText(companyProcess.calcWeight.toString(false));
        txtVrkme2.setText(companyProcess.calcWeight.getUOM());      
        
        setStatus("Aðýrlýk hesaplandý, kaydedebilirsiniz");
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnWeigh1ActionPerformed

    private void btnWeigh1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeigh1jButton1ActionPerformed
        
    }//GEN-LAST:event_btnWeigh1jButton1ActionPerformed

    private void btnPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlateActionPerformed
        
        enablePlate(false);
        connectToSql();
        
        companyProcess = new CompanyProcess();
        
        try
        {
            companyProcess.setVehicles(txtPlate.getText(), txtPlate2.getText());
        }
        catch(Exception ex)
        {
            setStatus("Tartým hatasý: " + ex.toString());
            enablePlate(true);
            return;
        }
        
        txtWeight1.setText(companyProcess.emptyWeight.toString(false));
        txtVrkme1.setText(companyProcess.emptyWeight.getUOM());
        
        setStatus("Lütfen tartýmý gerçekleþtirin");
        btnWeigh1.setEnabled(true);
    }//GEN-LAST:event_btnPlateActionPerformed
    
    private void enablePlate(boolean Enabled)
    {
        txtPlate.setEditable(false);
        txtPlate2.setEditable(false);
        btnPlate.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCompany().setVisible(true);
            }
        });
    }
    
    private boolean connectToSql()
    {
        try
        {
            Main.sql.connect();
            return true;
        }
        catch(Exception ex)
        {
            Main.appendLog("SQL baðlantý hatasý: " + ex.toString());
            setStatus("SQL baðlantý hatasý");
            return false;
        }        
    } 
    
    public void setStatus(String Status)
    {
        lblStatus.setText(Status);
    }       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPlate;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnWeigh1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtPlate2;
    private javax.swing.JTextField txtVrkme1;
    private javax.swing.JTextField txtVrkme2;
    private javax.swing.JTextField txtVrkmeTotal;
    private javax.swing.JTextField txtWeight1;
    private javax.swing.JTextField txtWeight2;
    private javax.swing.JTextField txtWeightTotal;
    // End of variables declaration//GEN-END:variables
    
}
