/*
 * frmFree.java
 *
 * Created on 24 Kasým 2007 Cumartesi, 14:48
 */

package askan;
import askan.configuration.*;
import askan.systems.*;
import askan.steelyard.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author  Kerem
 */
public class frmFree extends javax.swing.JFrame {
    
    private FreeProcess freeProcess;
    private TwoWaySerialComm.TRUCK_STATUS truckStatus;
    private boolean itemSaved;
    
    /** Creates new form frmFree */
    public frmFree() {
        initComponents();
    }
    
    public frmFree(TwoWaySerialComm.TRUCK_STATUS TruckStatus)
    {
        ActionMap am;
        InputMap im;
        KeyStroke ks;          
        
        initComponents();
        freeProcess = new FreeProcess();
        truckStatus = TruckStatus;
        
        Action plateActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnPlateActionPerformed(actionEvent);
            }
          };        
        am = btnPlate.getActionMap();
        im = btnPlate.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        im.put(ks, "plate");
        am.put("plate", plateActionListener);    
        
        Action saveActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnSaveActionPerformed(actionEvent);
            }
          };        
        am = btnSave.getActionMap();
        im = btnSave.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F11, 0);
        im.put(ks, "save");
        am.put("save", saveActionListener);  
        
        Action weighActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnWeighActionPerformed(actionEvent);
            }
          };        
        am = btnWeigh.getActionMap();
        im = btnWeigh.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0);
        im.put(ks, "weigh");
        am.put("weigh", weighActionListener); 
        
        Action printActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnPrintActionPerformed(actionEvent);
            }
          };        
        am = btnPrint.getActionMap();
        im = btnPrint.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0);
        im.put(ks, "print");
        am.put("print", printActionListener);          
        
        Action closeActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnCloseActionPerformed(actionEvent);
            }
          };        
        am = btnClose.getActionMap();
        im = btnClose.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        im.put(ks, "close");
        am.put("close", closeActionListener);          
        
        this.setTitle("Serbest Araç Tartýmý");
        
        if (TruckStatus == TwoWaySerialComm.TRUCK_STATUS.EMPTY)
        {
            txtWeightEmpty.setEditable(Main.config.intParam.manualWeight);
            txtVrkmeEmpty.setEditable(Main.config.intParam.manualWeight);
        }
        else
        {
            txtWeightFull.setEditable(Main.config.intParam.manualWeight);
            txtVrkmeFull.setEditable(Main.config.intParam.manualWeight);        
        }
        
        setStatus("Lütfen plakayý girin ve SEÇ düðmesine týklayýn");
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPlate = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtWeightEmpty = new javax.swing.JTextField();
        txtWeightFull = new javax.swing.JTextField();
        txtWeightCalc = new javax.swing.JTextField();
        txtVrkmeEmpty = new javax.swing.JTextField();
        txtVrkmeFull = new javax.swing.JTextField();
        txtVrkmeCalc = new javax.swing.JTextField();
        btnWeigh = new javax.swing.JButton();
        btnPlate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/save_16.gif"))); // NOI18N
        btnSave.setText("F11 - Kaydet");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/delete_16.gif"))); // NOI18N
        btnClose.setText("F12 - Kapat");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblStatus.setText("...");
        lblStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Plaka");

        txtPlate.setFont(new java.awt.Font("Tahoma", 0, 14));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Boþ Aðýrlýk");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("Dolu Aðýrlýk");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("Tartýlan Aðýrlýk");

        txtWeightEmpty.setEditable(false);
        txtWeightEmpty.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtWeightFull.setEditable(false);
        txtWeightFull.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtWeightCalc.setEditable(false);
        txtWeightCalc.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeEmpty.setEditable(false);
        txtVrkmeEmpty.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeFull.setEditable(false);
        txtVrkmeFull.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeCalc.setEditable(false);
        txtVrkmeCalc.setFont(new java.awt.Font("Tahoma", 0, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtWeightCalc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeightFull, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeightEmpty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVrkmeEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrkmeFull, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrkmeCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtWeightEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtWeightFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtWeightCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtVrkmeEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVrkmeFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVrkmeCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnWeigh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/applications_16.gif"))); // NOI18N
        btnWeigh.setText("F5 - Tart");
        btnWeigh.setEnabled(false);
        btnWeigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeighActionPerformed(evt);
                btnWeighjButton1ActionPerformed(evt);
            }
        });

        btnPlate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/add_16.gif"))); // NOI18N
        btnPlate.setText("F1 - Seç");
        btnPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Firma");

        txtCompany.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Notlar");

        txtNote.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/S_B_PRNT.gif"))); // NOI18N
        btnPrint.setText("F10");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWeigh, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnPlate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(txtNote, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                                .addGap(127, 127, 127)))))
                .addContainerGap())
            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnPlate))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWeigh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose)
                        .addComponent(btnSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void saveEnable(boolean Enable)
    {
        btnSave.setEnabled(itemSaved ? false : Enable);
        btnPrint.setEnabled(Enable);
    }
    
    private void transferFormToObject()
    {
        freeProcess.trmtyp = askan.systems.Util.formatPlate(txtPlate.getText());
        freeProcess.notes = txtNote.getText();
        freeProcess.company = txtCompany.getText();
        if (freeProcess.truckStatus == null) freeProcess.truckStatus = truckStatus;

        if (truckStatus == TwoWaySerialComm.TRUCK_STATUS.EMPTY)
        {
            freeProcess.passedEmpty = true;
            freeProcess.dateEmpty = Calendar.getInstance();
        }

        if (truckStatus == TwoWaySerialComm.TRUCK_STATUS.FULL)
        {
            freeProcess.passedFull = true;
            freeProcess.dateFull = Calendar.getInstance();
        }        
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveEnable(false);
        
        if (!itemSaved) {
            try {
                transferFormToObject();
                
                if (
                        (truckStatus == TwoWaySerialComm.TRUCK_STATUS.EMPTY && 
                         freeProcess.passedEmpty && !freeProcess.passedFull)
                        ||
                        (truckStatus == TwoWaySerialComm.TRUCK_STATUS.FULL && 
                         freeProcess.passedFull && !freeProcess.passedEmpty)
                   )
                {
                    freeProcess.insert(Main.sql);
                }
                else
                {
                    freeProcess.update();
                }
                
                setStatus("Aðýrlýk kaydedildi");
                itemSaved = true;
            } catch(Exception ex) {
                setStatus("Aðýrlýk kaydedilirken bir hata oluþtu");
                Main.appendLog(freeProcess.trmtyp + " aracýna ait aðýrlýk kaydedilirken bir hata oluþtu: " + ex.toString());
                saveEnable(true);
                return;
            }
        }
        
        saveEnable(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnWeighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeighActionPerformed
        btnWeigh.setEnabled(false);
        
        if (truckStatus == TwoWaySerialComm.TRUCK_STATUS.FULL)
        {
            if (Main.config.intParam.manualWeight)
            {
                try
                {
                freeProcess.fullWeight = new Weight();
                freeProcess.fullWeight.setWeight(txtWeightFull.getText(), txtVrkmeFull.getText());
                }
                catch(Exception ex)
                {
                    Main.appendLog("Aðýrlýk hatasý: " + ex.toString());
                    setStatus("Lütfen aðýrlýklarý kontrol edin");
                    return;
                }                
            }
            else
            {
                Main.steelYard.truckStatus = TwoWaySerialComm.truckStatus.FULL;
                freeProcess.fullWeight = Main.steelYard.getLastWeight();
                txtWeightFull.setText(freeProcess.fullWeight.toString(false));
                txtVrkmeFull.setText(freeProcess.fullWeight.getUOM());
            }
            
            if (freeProcess.passedEmpty)
            {
                freeProcess.calculateCalcWeight();
                txtWeightCalc.setText(freeProcess.calcWeight.toString(false));
                txtVrkmeCalc.setText(freeProcess.calcWeight.getUOM());
            }
        }
        
        if (truckStatus == TwoWaySerialComm.TRUCK_STATUS.EMPTY)
        {
            if (Main.config.intParam.manualWeight)
            {
                try
                {
                    freeProcess.emptyWeight = new Weight();
                    freeProcess.emptyWeight.setWeight(txtWeightEmpty.getText(), txtVrkmeEmpty.getText());
                }
                catch(Exception ex)
                {
                    Main.appendLog("Aðýrlýk hatasý: " + ex.toString());
                    setStatus("Lütfen aðýrlýklarý kontrol edin");
                    return;
                }
            }
            else
            {
                Main.steelYard.truckStatus = TwoWaySerialComm.truckStatus.EMPTY;
                freeProcess.emptyWeight = Main.steelYard.getLastWeight();
                txtWeightEmpty.setText(freeProcess.emptyWeight.toString(false));
                txtVrkmeEmpty.setText(freeProcess.emptyWeight.getUOM());
            }
            
            if (freeProcess.passedFull)
            {
                freeProcess.calculateCalcWeight();
                txtWeightCalc.setText(freeProcess.calcWeight.toString(false));
                txtVrkmeCalc.setText(freeProcess.calcWeight.getUOM());
            }
        }      
        
        setStatus("Tartým tamamlandý, kaydedip kapatabilirsiniz");
        saveEnable(true);

    }//GEN-LAST:event_btnWeighActionPerformed

    private void btnWeighjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeighjButton1ActionPerformed
        
    }//GEN-LAST:event_btnWeighjButton1ActionPerformed

    public void setStatus(String Status)
    {
        lblStatus.setText(Status);
    }         
    
    private boolean connectToSql()
    {
        try
        {
            Main.sql.connect();
            return true;
        }
        catch(Exception ex)
        {
            Main.appendLog("SQL baðlantý hatasý: " + ex.toString());
            setStatus("SQL baðlantý hatasý");
            return false;
        }        
    }           
    
    private void enableAfterPlateQuery(boolean Enabled)
    {
        txtPlate.setEditable(Enabled);
        btnPlate.setEnabled(Enabled);
    }      
    
    private void btnPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlateActionPerformed
      
        connectToSql();
        
        // Ekraný kapat
        setStatus("Araç sorgulanýyor...");
        enableAfterPlateQuery(false);
        
        // Bu araç daha önce girilmiþ mi, ilk kez mi giriliyor?
        FreeProcess f = FreeProcess.getActiveFreeProcess(askan.systems.Util.formatPlate(txtPlate.getText()));
        if (f == null)
        {
            freeProcess.truckStatus = truckStatus;
        }
        else
        {
            if (
                    (truckStatus == TwoWaySerialComm.TRUCK_STATUS.EMPTY && f.passedEmpty)
                    ||
                    (truckStatus == TwoWaySerialComm.TRUCK_STATUS.FULL && f.passedFull)
               )
            {
                if (askan.systems.Util.confirmStep(this, "Bu araca ait açýk bir tartým gözüküyor! \nEðer devam ederseniz, eski kayýt iptal edilecektir.")) 
                {
                    try
                    {
                        FreeProcess.cancelActiveFreeProcesses(txtPlate.getText());
                    }
                    catch(Exception ex)
                    {
                        setStatus("Ýptal sýrasýnda bir hata oluþtu");
                        Main.appendLog(txtPlate.getText() + " plakasýna ait eski kayýtlar iptal edilirken bir hata oluþtu: " + ex.toString());
                        return;
                    }
                }  
                else
                {
                    btnPlate.setEnabled(true);
                    setStatus("Lütfen plakayý girip sorgulayýn");
                    return;
                }
            }
            
            freeProcess = f;
        }
        
        enableAfterPlateQuery(true);
        
        // Aktarým
        if (freeProcess.truckStatus == TwoWaySerialComm.TRUCK_STATUS.EMPTY && freeProcess.passedEmpty)
        {
            txtWeightEmpty.setText(freeProcess.emptyWeight.toString(false));
            txtVrkmeEmpty.setText(freeProcess.emptyWeight.getUOM());
        }
        if (freeProcess.truckStatus == TwoWaySerialComm.TRUCK_STATUS.FULL && freeProcess.passedFull)
        {
            txtWeightFull.setText(freeProcess.fullWeight.toString(false));
            txtVrkmeFull.setText(freeProcess.fullWeight.getUOM());            
        }
        
        txtNote.setText(freeProcess.notes == null ? "" : freeProcess.notes);
        txtCompany.setText(freeProcess.company == null ? "" : freeProcess.company);
        
        btnWeigh.setEnabled(true);
        setStatus("Lütfen aracý tartýn");
    }//GEN-LAST:event_btnPlateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if (freeProcess.id == 0)
        {
            setStatus("Lütfen yazdýrmadan önce kaydedin");
            return;
        }
        
        btnPrint.setEnabled(false);
        this.setStatus("Kantar fiþi yazdýrýlýyor, lütfen bekleyin");
        if (!itemSaved) transferFormToObject();
        freeProcess.print();
        setStatus("Kantar fiþi yazdýrýldý");
        btnPrint.setEnabled(true);
}//GEN-LAST:event_btnPrintActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFree().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPlate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnWeigh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtVrkmeCalc;
    private javax.swing.JTextField txtVrkmeEmpty;
    private javax.swing.JTextField txtVrkmeFull;
    private javax.swing.JTextField txtWeightCalc;
    private javax.swing.JTextField txtWeightEmpty;
    private javax.swing.JTextField txtWeightFull;
    // End of variables declaration//GEN-END:variables
    
}
