/*
 * frmMMEmpty.java
 *
 * Created on 10 Kasým 2007 Cumartesi, 15:22
 */

package askan;
import askan.configuration.*;
import askan.systems.*;
import askan.steelyard.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author  Kerem
 */
public class frmMMEmpty extends javax.swing.JFrame {
    
    private PurchProcess purchProcess;
    private ArrayList wareHouses, drivers;
    private boolean itemSaved;
    
    /** Creates new form frmMMEmpty */
    public frmMMEmpty() {
        ActionMap am;
        InputMap im;
        KeyStroke ks;        
        
        initComponents();
        
        Action plateActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnPlateActionPerformed(actionEvent);
            }
          };        
        am = btnPlate.getActionMap();
        im = btnPlate.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        im.put(ks, "plate");
        am.put("plate", plateActionListener);        
        
        Action weighActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnWeighActionPerformed(actionEvent);
            }
          };        
        am = btnWeigh.getActionMap();
        im = btnWeigh.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0);
        im.put(ks, "weigh");
        am.put("weigh", weighActionListener);
        
        Action saveActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnSaveActionPerformed(actionEvent);
            }
          };        
        am = btnSave.getActionMap();
        im = btnSave.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F11, 0);
        im.put(ks, "save");
        am.put("save", saveActionListener);  
        
        Action printActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnPrintActionPerformed(actionEvent);
            }
          };        
        am = btnPrint.getActionMap();
        im = btnPrint.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0);
        im.put(ks, "print");
        am.put("print", printActionListener);        
        
        Action closeActionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
              btnCloseActionPerformed(actionEvent);
            }
          };        
        am = btnClose.getActionMap();
        im = btnClose.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ks = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        im.put(ks, "close");
        am.put("close", closeActionListener);            
        
        this.setTitle("Satýnalma Boþ Tartým");
        setStatus("Lütfen plakayý girin ve SEÇ düðmesine basýn");
        
        txtWeightEmpty.setEditable(Main.config.intParam.manualWeight);
        txtVrkmeEmpty.setEditable(Main.config.intParam.manualWeight);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPlate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVendor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JTextField();
        btnPlate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtQuantityRequested = new javax.swing.JTextField();
        txtWeightEmpty = new javax.swing.JTextField();
        txtWeightFull = new javax.swing.JTextField();
        txtWeightCalc = new javax.swing.JTextField();
        txtVrkmeRequested = new javax.swing.JTextField();
        txtVrkmeEmpty = new javax.swing.JTextField();
        txtVrkmeFull = new javax.swing.JTextField();
        txtVrkmeCalc = new javax.swing.JTextField();
        btnWeigh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cmbWarehouse = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIrsal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbDriver = new javax.swing.JComboBox();
        chkInspect = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Plaka");

        txtPlate.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Satýcý");

        txtVendor.setEditable(false);
        txtVendor.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("Malzeme");

        txtMaterial.setEditable(false);
        txtMaterial.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnPlate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/add_16.gif"))); // NOI18N
        btnPlate.setText("F1 - Seç");
        btnPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlateActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Ýrsaliye Miktarý");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Boþ Aðýrlýk");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("Dolu Aðýrlýk");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("Tartýlan Aðýrlýk");

        txtQuantityRequested.setEditable(false);
        txtQuantityRequested.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtWeightEmpty.setEditable(false);
        txtWeightEmpty.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtWeightFull.setEditable(false);
        txtWeightFull.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtWeightCalc.setEditable(false);
        txtWeightCalc.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeRequested.setEditable(false);
        txtVrkmeRequested.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeEmpty.setEditable(false);
        txtVrkmeEmpty.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeFull.setEditable(false);
        txtVrkmeFull.setFont(new java.awt.Font("Tahoma", 0, 14));

        txtVrkmeCalc.setEditable(false);
        txtVrkmeCalc.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnWeigh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/applications_16.gif"))); // NOI18N
        btnWeigh.setText("F5 - Tart");
        btnWeigh.setEnabled(false);
        btnWeigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeighActionPerformed(evt);
                btnWeighjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtWeightCalc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeightEmpty, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeightFull, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantityRequested, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVrkmeEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrkmeRequested, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrkmeFull, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrkmeCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnWeigh, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWeigh, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVrkmeRequested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtWeightEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVrkmeEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtWeightFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVrkmeFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtWeightCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVrkmeCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel11.setText("Depo");

        cmbWarehouse.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/save_16.gif"))); // NOI18N
        btnSave.setText("F11 - Kaydet");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/delete_16.gif"))); // NOI18N
        btnClose.setText("F12 - Kapat");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblStatus.setText("...");
        lblStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel13.setText("Notlar");

        txtNote.setEditable(false);
        txtNote.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/S_B_PRNT.gif"))); // NOI18N
        btnPrint.setText("F10");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setText("Ýrsaliye");

        txtIrsal.setEditable(false);
        txtIrsal.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("Þöför");

        cmbDriver.setFont(new java.awt.Font("Tahoma", 0, 14));

        chkInspect.setText("Ýncelensin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendor, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(cmbWarehouse, 0, 376, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(67, 67, 67)
                                .addComponent(cmbDriver, 0, 305, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(txtIrsal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(64, 64, 64)
                        .addComponent(txtNote, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkInspect)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addGap(9, 9, 9)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cmbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtIrsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(chkInspect)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnPrint)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean connectToSql()
    {
        try
        {
            Main.sql.connect();
            return true;
        }
        catch(Exception ex)
        {
            Main.appendLog("SQL baðlantý hatasý: " + ex.toString());
            setStatus("SQL baðlantý hatasý");
            return false;
        }        
    }        
    
    private void btnPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlateActionPerformed
        connectToSql();
        
        // Ekraný kapat
        setStatus("Araç sorgulanýyor...");
        enableAfterPlateQuery(false);
        
        // Process'i bul
        try {
            purchProcess = new PurchProcess();
            boolean b = purchProcess.fillFromPlate(txtPlate.getText());
            if (!b) {
                setStatus(txtPlate.getText() + " plakalý araç henüz dolu kantardan geçmemiþ");
                enableAfterPlateQuery(true);
                return;
            }
        } catch(Exception ex) {
            Main.appendLog("Plaka sorgusu sýrasýnda hata: " + ex.toString());
            enableAfterPlateQuery(true);
            return;
        }
        
        if (!purchProcess.passedFull) {
            setStatus(txtPlate.getText() + " plakalý araç henüz dolu kantardan geçmemiþ");
            enableAfterPlateQuery(true);
            return;
        }
        
        if (purchProcess.passedEmpty) {
            setStatus(txtPlate.getText() + " plakalý araç dolu kantarda zaten tartýlmýþ");
            enableAfterPlateQuery(true);
            return;
        }
        
        // Aktarým
        txtVendor.setText(purchProcess.getVendorDisplayText());
        txtMaterial.setText(purchProcess.getMaterialDisplayText());
        
        txtQuantityRequested.setEditable(true);
        txtVrkmeRequested.setEditable(true);
        
        txtWeightFull.setText(purchProcess.fullWeight.toString(false));
        txtVrkmeFull.setText(Material.getUOM(purchProcess.fullWeight.uom));
        
        if (purchProcess.inspect)
        {
            chkInspect.setEnabled(false);
            chkInspect.setSelected(true);
        }
        
        btnWeigh.setEnabled(true);
        setStatus("Lütfen boþ aracý tartýn");
    }//GEN-LAST:event_btnPlateActionPerformed

    private void enableAfterPlateQuery(boolean Enabled)
    {
        txtPlate.setEditable(Enabled);
        btnPlate.setEnabled(Enabled);
    }        
    
    public void setStatus(String Status)
    {
        lblStatus.setText(Status);
    }     
    
    private void btnWeighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeighActionPerformed
        btnWeigh.setEnabled(false);
        
        TwoWaySerialComm.truckStatus = TwoWaySerialComm.TRUCK_STATUS.EMPTY;
        if (Main.config.intParam.manualWeight)
        {
            try
            {
            purchProcess.emptyWeight = new Weight();
            purchProcess.emptyWeight.setWeight(txtWeightEmpty.getText(), txtVrkmeEmpty.getText());
            }
                catch(Exception ex)
                {
                    Main.appendLog("Aðýrlýk hatasý: " + ex.toString());
                    setStatus("Lütfen aðýrlýklarý kontrol edin");
                    return;
                }
        }
        else
        {
            purchProcess.emptyWeight = Main.steelYard.getLastWeight();
        }
        
        
        if (purchProcess.emptyWeight.getWeight() == 0) {
            setStatus("Tartým hatasý");
            btnWeigh.setEnabled(true);
            return;
        } else {
            truckWeighted();
        }
    }//GEN-LAST:event_btnWeighActionPerformed

        private void truckWeighted()
    {
        purchProcess.calculateCalcWeight();
        
        txtWeightEmpty.setText(purchProcess.emptyWeight.toString(false));
        txtVrkmeEmpty.setText(Material.getUOM(purchProcess.emptyWeight.uom));
        
        txtWeightCalc.setText(purchProcess.calcWeight.toString(false));
        txtVrkmeCalc.setText(Material.getUOM(purchProcess.calcWeight.uom));
        
        // Devam
        setStatus("Aðýrlýk hesaplandý, diðer bilgileri tamamlayýp kaydedebilirsiniz");
        txtNote.setEditable(true);
        txtIrsal.setEditable(true);
        
        wareHouses = new ArrayList();
        try
        {
            cmbWarehouse.removeAllItems();
            cmbWarehouse.addItem("-- Lütfen Depo Seçin--");
            wareHouses = WareHouse.getAll(WareHouse.USAGE_GOAL.PURCHASE);
            for (int n = 0; n < wareHouses.size(); n++)
            {
                WareHouse w = (WareHouse) wareHouses.get(n);
                cmbWarehouse.addItem(w.getDisplayText());
                
                if (Main.config.steelyardParam.lgorm != null && Main.config.steelyardParam.lgorm.lgort.equals(w.lgort))
                {
                    cmbWarehouse.setSelectedIndex(n + 1);
                }                
            }
        }
        catch(Exception ex)
        {
            Main.appendLog("Depo yerleri çekilemedi: " + ex.toString());
        }
        
        paintDrivers();
        cmbDriver.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnPrint.setEnabled(true);
    }
        
    private void paintDrivers()
    {
        connectToSql();
        drivers = new ArrayList();
        try
        {
            cmbDriver.setEditable(true);
            cmbDriver.removeAllItems();
            cmbDriver.addItem("-- Lütfen Þöför Seçin veya Yazýn--");
            drivers = Driver.getDriversOfVehicle(txtPlate.getText());
            for (int n = 0; n < drivers.size(); n++)
            {
                Driver d = (Driver) drivers.get(n);
                cmbDriver.addItem(d.getDisplayText());
            }
            
            if (drivers.size() == 1) cmbDriver.setSelectedIndex(1);
        }
        catch(Exception ex)
        {
            Main.appendLog("Þöförler çekilemedi: " + ex.toString());
        }
        cmbDriver.setEditable(true);        
    }           
    
    private void btnWeighjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeighjButton1ActionPerformed
        
    }//GEN-LAST:event_btnWeighjButton1ActionPerformed

    public void saveEnable(boolean Enable)
    {
        btnSave.setEnabled(itemSaved ? false : Enable);
        cmbWarehouse.setEnabled(Enable);
        txtNote.setEnabled(Enable);
        btnPrint.setEnabled(Enable);
        txtQuantityRequested.setEnabled(Enable);
        txtVrkmeRequested.setEnabled(Enable);
    }    
    
    private void transferFormToObjectPreSave()
    {
        purchProcess.emptyNote = txtNote.getText();
        purchProcess.inspect = chkInspect.isSelected();

        if (cmbWarehouse.getSelectedIndex() > 0) {
            purchProcess.wareHouse = (WareHouse) wareHouses.get(cmbWarehouse.getSelectedIndex() - 1);
        } else {
            purchProcess.wareHouse = null;
        }        
        
        if (purchProcess.dateEmpty == null) purchProcess.dateEmpty = Calendar.getInstance();
        
        if (cmbDriver.getSelectedIndex() <= 0)
        {
            purchProcess.sofidManual = cmbDriver.getSelectedItem().toString();
            purchProcess.driver = null;
        }
        else
        {
            purchProcess.driver = (Driver) drivers.get(cmbDriver.getSelectedIndex() - 1);
        }      
        
        try
        {
            purchProcess.lfimg = new Weight();
            if (txtQuantityRequested.getText() == null || txtQuantityRequested.getText().length() == 0)
            {
                purchProcess.lfimg.setWeight(0, "TON");
            }
            else
            {
                purchProcess.lfimg.setWeight(txtQuantityRequested.getText(), txtVrkmeRequested.getText());
            }
        }
        catch(Exception ex)
        {
            setStatus("Lütfen aðýrlýklarý kontrol edin");
            saveEnable(true);
            return;
        }     
        
        purchProcess.irsal = txtIrsal.getText();
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        btnSave.setEnabled(false);
        
        if (!itemSaved) {
            saveEnable(false);
            transferFormToObjectPreSave();
            
            try {
                purchProcess.saveEmptyWeight();
                setStatus("Boþ aðýrlýk kaydedildi, kamyon tesisten çýkabilir");
                itemSaved = true;
                btnPrint.setEnabled(true);
                chkInspect.setEnabled(false);
            } catch(Exception ex) {
                setStatus("Boþ aðýrlýk kaydedilirken bir hata oluþtu");
                Main.appendLog(purchProcess.getPlate() + " aracýna ait boþ aðýrlýk kaydedilirken bir hata oluþtu: " + ex.toString());
                saveEnable(true);
                return;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        btnPrint.setEnabled(false);
        if (!itemSaved) transferFormToObjectPreSave();
        this.setStatus("Kantar fiþi yazdýrýlýyor, lütfen bekleyin");
        purchProcess.printEmpty();
        setStatus("Kantar fiþi yazdýrýldý");
        btnPrint.setEnabled(true);
}//GEN-LAST:event_btnPrintActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmMMEmpty().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPlate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnWeigh;
    private javax.swing.JCheckBox chkInspect;
    private javax.swing.JComboBox cmbDriver;
    private javax.swing.JComboBox cmbWarehouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtIrsal;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtQuantityRequested;
    private javax.swing.JTextField txtVendor;
    private javax.swing.JTextField txtVrkmeCalc;
    private javax.swing.JTextField txtVrkmeEmpty;
    private javax.swing.JTextField txtVrkmeFull;
    private javax.swing.JTextField txtVrkmeRequested;
    private javax.swing.JTextField txtWeightCalc;
    private javax.swing.JTextField txtWeightEmpty;
    private javax.swing.JTextField txtWeightFull;
    // End of variables declaration//GEN-END:variables
    
}
