/*
 * frmMain.java
 *
 * Created on 20 Ekim 2007 Cumartesi, 13:51
 */

package askan;

import askan.configuration.Config;
import askan.steelyard.TwoWaySerialComm.TRUCK_STATUS;
import java.awt.*;
import java.awt.event.*;
import java.util.*;

/**
 *
 * @author  Kerem
 */
public class frmMain extends javax.swing.JFrame {
    
    public Config c;
    
    /** Creates new form frmMain */
    public frmMain() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("truck.gif"));
        lblOperator.setText(Main.operatorName);
        this.setTitle("As Kantar 1.1.7");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSDSevk = new javax.swing.JButton();
        btnSDEmpty = new javax.swing.JButton();
        btnSDFull = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMMEmpty = new javax.swing.JButton();
        btnMMFull = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnETCEmpty = new javax.swing.JButton();
        btnETCFull = new javax.swing.JButton();
        btnETCComp = new javax.swing.JButton();
        lblOperator = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuSync = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("As Kantar");
        setFont(new java.awt.Font("Courier New", 0, 14));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Müþteriye Satýþ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 24));

        btnSDSevk.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnSDSevk.setText("Sevkiyat");
        btnSDSevk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSDSevkActionPerformed(evt);
            }
        });

        btnSDEmpty.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnSDEmpty.setText("Boþ Tart");
        btnSDEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSDEmptyActionPerformed(evt);
            }
        });

        btnSDFull.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnSDFull.setText("Dolu Tart");
        btnSDFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSDFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSDSevk, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnSDEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSDFull, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSDSevk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSDEmpty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSDFull)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mal Kabul", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 24));

        btnMMEmpty.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnMMEmpty.setText("Boþ Tart");
        btnMMEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMEmptyActionPerformed(evt);
            }
        });

        btnMMFull.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnMMFull.setText("Dolu Tart");
        btnMMFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMMEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMMFull, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnMMEmpty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMMFull)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serbest Tartým", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 24));

        btnETCEmpty.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnETCEmpty.setText("Boþ Tart");
        btnETCEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnETCEmptyActionPerformed(evt);
            }
        });

        btnETCFull.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnETCFull.setText("Dolu Tart");
        btnETCFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnETCFullActionPerformed(evt);
            }
        });

        btnETCComp.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnETCComp.setText("Þirket Aracý Tart");
        btnETCComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnETCCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnETCEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnETCFull, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnETCComp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnETCEmpty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnETCFull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnETCComp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblOperator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperator.setText("*");
        lblOperator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/logo_czm1_t.jpg"))); // NOI18N

        menuFile.setText("Dosya");

        menuSync.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/S_B_REFR.gif"))); // NOI18N
        menuSync.setText("Senkronize Et");
        menuSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSyncActionPerformed(evt);
            }
        });
        menuFile.add(menuSync);
        menuFile.add(jSeparator1);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/S_B_CANC.gif"))); // NOI18N
        menuExit.setText("Çýkýþ");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        menuHelp.setText("Yardým");

        menuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/askan/binaries/S_B_PRSH.gif"))); // NOI18N
        menuAbout.setText("Hakkýnda...");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOperator, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOperator)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSDFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSDFullActionPerformed
        frmSDFull f = new frmSDFull();
        f.setVisible(true);
    }//GEN-LAST:event_btnSDFullActionPerformed

    private void btnSDEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSDEmptyActionPerformed
        frmSDEmpty f = new frmSDEmpty();
        f.setVisible(true);
    }//GEN-LAST:event_btnSDEmptyActionPerformed

    private void btnSDSevkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSDSevkActionPerformed
        frmSDSevk f = new frmSDSevk();
        f.setVisible(true);
    }//GEN-LAST:event_btnSDSevkActionPerformed

    private void btnMMFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMFullActionPerformed
        frmMMFull f = new frmMMFull();
        f.setVisible(true);
    }//GEN-LAST:event_btnMMFullActionPerformed

    private void btnMMEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMEmptyActionPerformed
        frmMMEmpty f = new frmMMEmpty();
        f.setVisible(true);
    }//GEN-LAST:event_btnMMEmptyActionPerformed

    private void btnETCFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnETCFullActionPerformed
        frmFree f = new frmFree(TRUCK_STATUS.FULL);
        f.setVisible(true);
    }//GEN-LAST:event_btnETCFullActionPerformed

    private void btnETCEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnETCEmptyActionPerformed
        frmFree f = new frmFree(TRUCK_STATUS.EMPTY);
        f.setVisible(true);
    }//GEN-LAST:event_btnETCEmptyActionPerformed

    private void btnETCCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnETCCompActionPerformed
        frmCompany f = new frmCompany();
        f.setVisible(true);
}//GEN-LAST:event_btnETCCompActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        processEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        frmAbout fa = new frmAbout();
        fa.setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSyncActionPerformed
        Main.syncMaster.doSync();
    }//GEN-LAST:event_menuSyncActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }      
    
    public void setSqlState(boolean Alive)
    {
        btnETCEmpty.setEnabled(Alive && Main.config.intParam.showFreeEmpty);
        btnETCFull.setEnabled(Alive && Main.config.intParam.showFreeFull);
        btnETCComp.setEnabled(Alive && Main.config.intParam.showCompany);
        btnMMEmpty.setEnabled(Alive && Main.config.intParam.showMMEmpty);
        btnMMFull.setEnabled(Alive && Main.config.intParam.showMMFull);
        btnSDEmpty.setEnabled(Alive && Main.config.intParam.showSDEmpty);
        btnSDFull.setEnabled(Alive && Main.config.intParam.showSDFull);        
        btnSDSevk.setEnabled(Alive && Main.config.intParam.showSDSevk);
    }
    
    public void setSteelYardState(boolean Alive)
    {
        btnETCEmpty.setEnabled(Alive && Main.config.intParam.showFreeEmpty);
        btnETCFull.setEnabled(Alive && Main.config.intParam.showFreeFull);
        btnETCComp.setEnabled(Alive && Main.config.intParam.showCompany);
        btnMMEmpty.setEnabled(Alive && Main.config.intParam.showMMFull);
        btnMMFull.setEnabled(Alive && Main.config.intParam.showMMFull);
        btnSDEmpty.setEnabled(Alive && Main.config.intParam.showSDEmpty);
        btnSDFull.setEnabled(Alive && Main.config.intParam.showSDFull);        
        //btnSDSevk.setEnabled(Alive && Main.config.intParam.showSDSevk);        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnETCComp;
    private javax.swing.JButton btnETCEmpty;
    private javax.swing.JButton btnETCFull;
    private javax.swing.JButton btnMMEmpty;
    private javax.swing.JButton btnMMFull;
    private javax.swing.JButton btnSDEmpty;
    private javax.swing.JButton btnSDFull;
    private javax.swing.JButton btnSDSevk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblOperator;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuSync;
    // End of variables declaration//GEN-END:variables
    
}
